// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwA4lL_3yzQ87dq4Xo1jzaj4P_DW69_Kk',
    appId: '1:923064126370:web:a4103073fabd0ffdbf80fb',
    messagingSenderId: '923064126370',
    projectId: 'maintenanceapp-27534',
    authDomain: 'maintenanceapp-27534.firebaseapp.com',
    storageBucket: 'maintenanceapp-27534.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYTFDo1H05kq6wumJcP5qe28h9K0J6hFI',
    appId: '1:923064126370:android:95f5c3a0e3302657bf80fb',
    messagingSenderId: '923064126370',
    projectId: 'maintenanceapp-27534',
    storageBucket: 'maintenanceapp-27534.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXy7ZC_kG0c7S5DQmZk_P65kElUvqRLz4',
    appId: '1:923064126370:ios:b367c83043a4bb37bf80fb',
    messagingSenderId: '923064126370',
    projectId: 'maintenanceapp-27534',
    storageBucket: 'maintenanceapp-27534.firebasestorage.app',
    iosBundleId: 'com.example.maintenanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXy7ZC_kG0c7S5DQmZk_P65kElUvqRLz4',
    appId: '1:923064126370:ios:b367c83043a4bb37bf80fb',
    messagingSenderId: '923064126370',
    projectId: 'maintenanceapp-27534',
    storageBucket: 'maintenanceapp-27534.firebasestorage.app',
    iosBundleId: 'com.example.maintenanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwA4lL_3yzQ87dq4Xo1jzaj4P_DW69_Kk',
    appId: '1:923064126370:web:a57cc972cc094686bf80fb',
    messagingSenderId: '923064126370',
    projectId: 'maintenanceapp-27534',
    authDomain: 'maintenanceapp-27534.firebaseapp.com',
    storageBucket: 'maintenanceapp-27534.firebasestorage.app',
  );
}
